name: battery_info_example
description: "Demonstrates how to use the battery_info plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  battery_info:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
