name: tsc_bluetooth_print_example
description: "Demonstrates how to use the tsc_bluetooth_print plugin."
publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  printing: ^5.12.0
  tsc_bluetooth_print:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
